-- ============================================================
-- Supabase Row Level Security (RLS) Policies
-- Run this in: Supabase Dashboard → SQL Editor
--
-- NOTE: This app uses SUPABASE_SERVICE_ROLE_KEY server-side,
-- which bypasses RLS. These policies are a defence-in-depth
-- measure — they would block any accidental direct client-side
-- access if the anon key were ever used in the wrong place.
-- ============================================================

-- ─── Enable RLS on all tables ────────────────────────────────
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE ratings ENABLE ROW LEVEL SECURITY;
ALTER TABLE newsletter ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_settings ENABLE ROW LEVEL SECURITY;

-- ─── posts ────────────────────────────────────────────────────
-- Anyone can read published posts
CREATE POLICY "Public can read published posts"
ON posts FOR SELECT
TO public
USING (published = 1);

-- No direct client inserts/updates/deletes — all writes go through
-- the server-side API using the service role key
CREATE POLICY "No direct client writes to posts"
ON posts FOR ALL
TO anon
USING (false);

-- ─── ratings ──────────────────────────────────────────────────
-- Anyone can read ratings (used for avg_rating calculation)
CREATE POLICY "Public can read ratings"
ON ratings FOR SELECT
TO public
USING (true);

-- Anyone can insert a rating (public feature)
CREATE POLICY "Public can submit ratings"
ON ratings FOR INSERT
TO public
WITH CHECK (score >= 1 AND score <= 5);

-- No client-side updates or deletes
CREATE POLICY "No direct client updates to ratings"
ON ratings FOR UPDATE
TO anon
USING (false);

-- ─── newsletter ───────────────────────────────────────────────
-- No public read access to newsletter list
CREATE POLICY "No public read on newsletter"
ON newsletter FOR SELECT
TO anon
USING (false);

-- Public can subscribe (insert their own email)
CREATE POLICY "Public can subscribe to newsletter"
ON newsletter FOR INSERT
TO public
WITH CHECK (true);

-- ─── admin_users ──────────────────────────────────────────────
-- Fully locked down — no client access at all
CREATE POLICY "No client access to admin_users"
ON admin_users FOR ALL
TO anon
USING (false);

-- ─── team_settings ────────────────────────────────────────────
-- Anyone can read team settings (used on /myteam page)
CREATE POLICY "Public can read team settings"
ON team_settings FOR SELECT
TO public
USING (true);

-- No direct client writes
CREATE POLICY "No direct client writes to team_settings"
ON team_settings FOR ALL
TO anon
USING (false);

-- ─── Storage: uploads bucket ──────────────────────────────────
-- Public can view uploaded files (thumbnails etc.)
CREATE POLICY "Public can view uploads"
ON storage.objects FOR SELECT
TO public
USING (bucket_id = 'uploads');

-- No direct client uploads — all uploads go through signed URLs
-- generated by the server-side API
CREATE POLICY "No direct client uploads"
ON storage.objects FOR INSERT
TO anon
WITH CHECK (false);

CREATE POLICY "No direct client deletes"
ON storage.objects FOR DELETE
TO anon
USING (false);
